language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.clone("https://github.com/sisl/POMDPs.jl"); Pkg.build("SARSOP"); Pkg.test("SARSOP", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SARSOP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
